name: Phishing Domain Check

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'List of URLs to scan (one per line)'
        required: true
        type: string
      output_format:
        description: 'Choose output format (terminal, json, csv)'
        required: true
        default: 'terminal'
        type: choice
        options:
          - terminal
          - json
          - csv

jobs:
  domain-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Save input URLs to file
        run: |
          echo "${{ github.event.inputs.urls }}" > workflow_urls.txt

      - name: Run phishing checker
        run: python phishing_checker.py workflow_urls.txt --output ${{ github.event.inputs.output_format }}

      - name: Upload results
        if: github.event.inputs.output_format != 'terminal'
        uses: actions/upload-artifact@v3
        with:
          name: phishing-check-results
          path: results.${{ github.event.inputs.output_format }}
          retention-days: 7